### ISSUE TITLE
Don't Use mavenLocal()

### ISSUE THREAD

**Issue by opticyclic** [manosbatsis/corbeans#25]
Don't use `mavenLocal()` in the `build.gradle`.

If you are dependent on jars in `mavenLocal()` then the code won't compile anywhere else.

If you aren't dependent on jars in `mavenLocal()` then you don't need it in the repositories list.

**Comment by manosbatsis** [comment]
`mavenLocal()` is only there for speed as it reuses any dependencies already there. It also helps with developing on SNAPSHOTS. If a dependency is not found there, gradle will try to find it using the other repositories configured.
