### ISSUE TITLE
trustStore-related node params are ignored

### ISSUE THREAD

**Issue by andiukov** [manosbatsis/corbeans#40]
Hi Manos,

There seems to be a problem with propagating the trustStore-related values from node params in corbeans config to the actual Corda client options.

There is no assignment of those options in NodeParams.Companion#mergeParams

This creates problems when RPC with SSL is used.

**Comment by manosbatsis** [comment]
Thanks for the report @andiukov, will fix for the next release, should be out in a day or two

**Comment by andiukov** [comment]
Great, thanks for prompt response.

**Comment by manosbatsis** [comment]
@andiukov the current version has been refactored to use RPC connection pooling. I'm afraid this makes your PR outdated (thank you so much for taking the time to submit one), but on the bright side it should solve the issue.

Please check out the [changelog](https://manosbatsis.github.io/corbeans/docs/changelog.html) and the updated [API overview](https://manosbatsis.github.io/corbeans/docs/component-api.html#api-overview) as the new version has some significant changes, notably in relation to not having node services autowired directly anymore (you get them from network service) and the new `withNodeRpcConnection` functions to use proxies.

Please feel free to close this issue after verifying trustStore-related params work as expected.

**Comment by andiukov** [comment]
@manosbatsis thanks for the fix and all the details.

Will try this out later this week.

I had a question regarding Corda compatibility - will latest (0.44) version work with Corda Enterprise 4.3?

**Comment by manosbatsis** [comment]
@andiukov  Yup, see also https://manosbatsis.github.io/corbeans/docs/faq.html#corda-enterprise

**Comment by manosbatsis** [comment]
BTW i've also updated [corbeans-yo-cordapp](https://github.com/manosbatsis/corbeans-yo-cordapp), should be helpful as an example while updating your own project

**Comment by andiukov** [comment]
Thanks! Will take a look.
